# Generated by Django 2.0.6 on 2020-04-09 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tuser',
            options={},
        ),
    ]
