# Generated by Django 2.0.6 on 2020-04-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200409_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuser',
            name='register_time',
            field=models.DateTimeField(auto_now_add=True, default='2020-01-01 12:00:00'),
            preserve_default=False,
        ),
    ]
